config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

setting_patterns = [
    path("apps/", include("risocrm.app_mgmt.urls")),
    path("filters/", include("risocrm.filters.urls")),
    path("choices/", include("risocrm.choices.urls")),
    # path("menus/", include("risocrm.menus.urls")),
    path("notices/", include("risocrm.notices.urls")),
    path("configs/", include("risocrm.configs.urls")),
]

urlpatterns = [
    path("", include("risocrm.dashboard.urls")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("risocrm.users.urls", namespace="users")),

    # System
    path("settings/", include(setting_patterns)),
    path("accounts/", include("allauth.urls")),

    # NOTIFICATION
    path("webpush/", include("webpush.urls")),
    # Your stuff: custom urls includes go here
    # Contact management
    path("contacts/", include("risocrm.contacts.urls")),
    path("notes/", include("risocrm.notes.urls")),
    path("activities/", include("risocrm.activities.urls")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

# Automation adding app

risocrm/app_mgmt/urls.py
"""
    App Urls
    App Management
"""
from django.urls import include, path

from risocrm.app_mgmt.apis import (get_field, get_field_label, get_field_type,
                                   get_foreign_data, get_label, get_module,
                                   make_migrations, migrate)
from risocrm.app_mgmt.views import create, delete, edit, index, view

app_name = 'app_mgmt'

fake_api = [
    path('make_migrations', make_migrations, name="make_migrations"),
    path('migrate', migrate, name="migrate"),
    path('get_module', get_module, name="get_module"),
    path('get_label', get_label, name="get_label"),
    path('get_field', get_field, name="get_field"),
    path('get_field_type', get_field_type, name="get_field_type"),
    path('get_foreign_data', get_foreign_data, name="get_foreign_data"),
    path('get_field_label', get_field_label, name="get_field_label"),
]

urlpatterns = [
    path("", index, name="index"),
    path("view", view, name="view"),
    path("create", create, name="create"),
    path('delete', delete, name="delete"),
    path("api/", include(fake_api)),
    path('<str:pk>', edit, name="edit"),
]

risocrm/choices/urls.py
"""
    App Urls
    Filters Router
"""
from django.urls import include, path

from risocrm.choices.apis import choice_childs, choice_list
from risocrm.choices.views import create, delete, edit, index, view

app_name = 'choices'


fake_api = [
    path('choice_list', choice_list, name="choice_list"),
    path('choice_childs/<str:pk>', choice_childs, name="choice_childs"),
]

urlpatterns = [
    path('api/', include(fake_api)),
    path('', index, name="list"),
    path('create', create, name="create"),
    path('delete', delete, name="delete"),
    path("view/<str:pk>/", view, name="view"),
    path('<str:pk>', edit, name="edit"),
]

risocrm/app_mgmt/models.py
"""
    App Model
    App Management
"""
from django.contrib.contenttypes.models import ContentType
from django.db.models import (CASCADE, BooleanField, CharField, ForeignKey,
                              IntegerField, Model, TextField)

FIELD_TYPE_CHOICES = (
    ('ForeignKey', 'ForeignKey'),
    ('ManyToManyField', 'ManyToManyField'),
    ('OneToOneField', 'OneToOneField'),
    ('CharField', 'CharField'),
    ('TextField', 'TextField'),
    ('BooleanField', 'BooleanField'),
    ('NullBooleanField', 'NullBooleanField'),
    ('DateField', 'DateField'),
    ('DateTimeField', 'DateTimeField'),
    ('TimeField', 'TimeField'),
    ('BigIntegerField', 'BigIntegerField'),
    ('IntegerField', 'IntegerField'),
    ('PositiveIntegerField', 'PositiveIntegerField'),
    ('PositiveSmallIntegerField', 'PositiveSmallIntegerField'),
    ('SmallIntegerField', 'SmallIntegerField'),
    ('DecimalField', 'DecimalField'),
    ('FloatField', 'FloatField'),
    ('FileField', 'FileField'),
    ('ImageField', 'ImageField'),
)

ON_DELETE_CHOICES = (
    ('CASCADE', 'CASCADE'),
    ('PROTECT', 'PROTECT'),
    ('SET_NULL', 'SET_NULL'),
    ('DO_NOTHING', 'DO_NOTHING')
)


class Dynafield(Model):
    """
        Dynamic Field
    """
    module = CharField(max_length=200, null=False, blank=False)
    name = CharField(max_length=250, null=False, blank=False)
    type = CharField(choices=FIELD_TYPE_CHOICES, max_length=150, null=False, blank=False)
    verbose_name = CharField(max_length=250, null=True, blank=True)
    fkmodule = CharField(max_length=200, null=True, blank=True)
    on_delete = CharField(choices=ON_DELETE_CHOICES, max_length=50, null=True, blank=True)

    default = CharField(max_length=200, null=True, blank=True)
    max_length = IntegerField(default=50, null=True, blank=True)
    group = CharField(max_length=250, null=True, blank=True)

    option = ForeignKey("choices.Choice", related_name="field_choices", on_delete=CASCADE, null=True, blank=True)

    is_base = BooleanField(default=False)

    def __str__(self):
        return F'Field {self.name} of {self.module}'

    def object(self):
        ctt = ContentType.objects.get(model=self.module.lower()).model_class()
        return [field for field in ctt._meta.concrete_fields if field.name == self.name][0]

risocrm/app_mgmt/forms.py
"""
    App Forms
    App Management
"""

from django.forms import (CheckboxInput, ModelForm, Select, TextInput,
                          inlineformset_factory, CharField)

from risocrm.app_mgmt.models import Dynafield


class DynafieldForm(ModelForm):

    class Meta:
        model = Dynafield
        fields = '__all__'
        widgets = {
            'type': Select(attrs={'class': 'form-control kt-select2'}),
            'module': Select(attrs={'class': 'form-control kt-select2'}),
            'fkmodule': Select(attrs={'class': 'form-control kt-select2'}),
            'group': Select(attrs={'class': 'form-control kt-select2'}),
            'option': Select(attrs={'class': 'form-control kt-select2'}),
            'default': Select(attrs={'class': 'form-control kt-select2'}),
        }

risocrm/app_mgmt/views.py
"""
    App Controller
    App Management
"""
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from risocrm.app_mgmt.forms import DynafieldForm
from risocrm.app_mgmt.helpers import get_group_distinct_tuple, model_render
from risocrm.app_mgmt.models import Dynafield
from risocrm.bases.apps import app_name_tuple, app_name_list
from risocrm.bases.variables import ADDED_APP, BASE_MODEL


@login_required()
def index(request):
    """
        Return all model on project
    """
    content = {
        'page_title': 'App Mangement',
        'table_title': 'Model list',
        'go_back_url': '',
        'go_back_desc': '',
    }
    model_list = app_name_list()
    # Remove Module of System
    content['models'] = list(set(model_list) ^ set(BASE_MODEL + ADDED_APP))

    return render(request, 'app_mgmt-list.html', content)


@login_required()
def view(request):
    """
        View detail field of 1 model
        Input is request parameter ?model=
    """
    model = request.GET.get("model", None)
    if not model:
        return redirect('app_mgmt:index')

    content = {
        'page_title': 'App Management',
        'table_title': 'List field of module' + model,
        'go_back_url': reverse('app_mgmt:index'),
        'go_back_desc': 'Model list',
        'model': model,
    }
    content['obj_list'] = Dynafield.objects.filter(module=model).order_by('group')

    return render(request, 'app_mgmt-view.html', content)


@login_required
def create(request):
    model = request.GET.get("model", "")
    context = {
        'page_title': 'App Mangement',
        'table_title': 'Create new field',
        'go_back_url': reverse('app_mgmt:index'),
        'go_back_desc': 'Model list',
        'model': model
    }

    if request.method == 'GET':
        form = DynafieldForm()
        form.fields['group'].widget.choices = [('', '----------')] + get_group_distinct_tuple(model)
        form.fields['module'].widget.choices = [('', '----------')] + app_name_tuple()
        form.fields['fkmodule'].widget.choices = [('', '----------')] + app_name_tuple()
        context['form'] = form
        return render(request, 'app_mgmt-edit.html', context)
    else:
        form = DynafieldForm(request.POST)
        form.fields['group'].widget.choices = [('', '----------')] + get_group_distinct_tuple(model)
        form.fields['module'].widget.choices = [('', '----------')] + app_name_tuple()
        form.fields['fkmodule'].widget.choices = [('', '----------')] + app_name_tuple()
        if not form.is_valid():
            context['form'] = form
            context['msg_error'] = "Dynafield form have error, please check again!"
            return render(request, 'app_mgmt-edit.html', context)
        else:
            menu = form.save(commit=False)
            menu.creator = request.user
            menu.save()
            model_render(menu.module, Dynafield.objects.filter(module=menu.module))
            messages.add_message(request, messages.SUCCESS, 'Create new field success')
            return redirect('app_mgmt:edit', menu.id)


@login_required
def edit(request, pk):
    obj = get_object_or_404(Dynafield, pk=pk)
    context = {
        'page_title': 'Dynafields',
        'table_title': F'Update {obj.name}',
        'go_back_url': F"{reverse('app_mgmt:view')}?model={obj.module}",
        'go_back_desc': 'Dynafields list',
        'menu': obj,
        'model': obj.module
    }

    if request.method == 'GET':
        form = DynafieldForm(instance=obj)
        form.fields['group'].widget.choices = [('', '----------')] + get_group_distinct_tuple()
        form.fields['module'].widget.choices = [('', '----------')] + app_name_tuple()
        form.fields['fkmodule'].widget.choices = [('', '----------')] + app_name_tuple()
        if obj.option:
            form.fields['default'].widget.choices = [('', '----------')] + [(m.id, m.value)
                                                                            for m in obj.option.choices_detail.all()]
        context['form'] = form
        return render(request, 'app_mgmt-edit.html', context)
    else:
        form = DynafieldForm(request.POST, instance=obj)
        form.fields['group'].widget.choices = [('', '----------')] + get_group_distinct_tuple()
        form.fields['module'].widget.choices = [('', '----------')] + app_name_tuple()
        form.fields['fkmodule'].widget.choices = [('', '----------')] + app_name_tuple()
        if obj.option:
            form.fields['default'].widget.choices = [('', '----------')] + [(m.id, m.value)
                                                                            for m in obj.option.choices_detail.all()]
        if not form.is_valid():
            context['form'] = form
            return render(request, 'app_mgmt-edit.html', context)
        else:
            menu = form.save()
            menu.last_modified_by = request.user
            menu.save()
            model_render(obj.module, Dynafield.objects.filter(module=obj.module))
            messages.add_message(request, messages.SUCCESS, 'Update field success')
            return redirect('app_mgmt:edit', menu.id)


@login_required
def delete(request):
    if request.method == 'POST':
        del_list = request.POST.get('idlist')
        if del_list is not None:
            _del_list = [int(id) for id in del_list[:-1].split(',')]
            for field in _del_list:
                try:
                    obj = Dynafield.objects.get(pk=field)
                    model_render(obj.module, Dynafield.objects.filter(module=obj.module))
                    obj.delete()
                except Exception:
                    raise Http404
    return redirect('app_mgmt:index')

risocrm/app_mgmt/templates/app_mgmt-edit.html
{% extends 'base.html' %}
{% load static %}
{% block css %} {% endblock css %}
{% block pagecss %}
{% comment %}
<link href="{% static 'plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" />
{% endcomment %}
{% endblock pagecss %}
{% block toolbar %}

{% endblock toolbar %} {% block content %}
<form action="{{request.get_full_path}}" method="post" class="validated">
	{% csrf_token %}
	<div class="kt-portlet kt-portlet--mobile kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile">
		<div class="kt-portlet__head kt-portlet__head--lg">
			<div class="kt-portlet__head-label">
				<span class="kt-portlet__head-icon">
					<i class="kt-font-brand"></i>
				</span>
				<h3 class="kt-portlet__head-title">
					{{table_title}}
				</h3>
			</div>
			<div class="kt-portlet__head-toolbar">
				<div class="kt-portlet__head-wrapper">
					<div class="kt-portlet__head-actions">
						&nbsp;
						<button type="submit" class="btn btn-success">
							<i class="la la-check" style="padding-right: 0px;"></i>
						</button>
						&nbsp;
						<a href="{{go_back_url}}" class="btn btn-secondary">
							<i class="la la-ban" style="padding-right: 0px;"></i>
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="kt-portlet__body">
			<div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
				<div class="row">
					<div class="col-sm-12">
						<div class="kt-portlet__body">
							<div class="form-group row">
								<div class="col-lg-3 d-none">
									<label>Module:</label>
									{{form.module}}
									{% for item in form.module.errors %}
									<div class="invalid-feedback">{{item}}</div>
									{% endfor %}
									<span class="form-text text-muted">Please select module</span>
								</div>
								<div class="col-lg-3 ">
									<label>Group:</label>
									{{form.group}}
									{% for item in form.group.errors %}
									<div class="invalid-feedback">{{item}}</div>
									{% endfor %}
									<span class="form-text text-muted">Please select group</span>
								</div>
								<div class="col-lg-3">
									<label>Field Name:</label>
									{{form.name}}
									{% for item in form.name.errors %}
									<div class="invalid-feedback">{{item}}</div>
									{% endfor %}
									<span class="form-text text-muted">Please enter field name</span>
								</div>
								<div class="col-lg-3">
									<label class="">Verbose Name:</label>
									{{form.verbose_name}}
									{% for item in form.verbose_name.errors %}
									<div class="invalid-feedback">{{item}}</div>
									{% endfor %}
									<span class="form-text text-muted">Please enter field verbose name</span>
								</div>
								<div class="col-lg-3" data-input-type>
									<label class="">Type:</label>
									{{form.type}}
									{% for item in form.type.errors %}
									<div class="invalid-feedback">{{item}}</div>
									{% endfor %}
									<span class="form-text text-muted">Please select field type</span>
								</div>
							</div>
							<div id="form-container" class="row">

							</div>
						</div>
					</div>
				</div>
			</div>

			<!--end: Datatable -->
		</div>

		<script type="text/html" id="hbs-fkmodule">
			<div class="col-lg-3">
			<label>FK Module:</label>
			{{form.fkmodule}}
			{% for item in form.fkmodule.errors %}
				<div class="invalid-feedback">{{item}}</div>
			{% endfor %}
			<span class="form-text text-muted">Select ForeignKey Module</span>
			</div>
		</script>

		<script type="text/html" id="hbs-ondelete">
		
			<div class="col-lg-3">
			<label class="">On delete:</label>
			{{form.on_delete}}
			{% for item in form.on_delete.errors %}
				<div class="invalid-feedback">{{item}}</div>
			{% endfor %}
			<span class="form-text text-muted">On delete event</span>
			</div>
		</script>

		<script type="text/html" id="hbs-option">
			<div class="col-lg-3">
				<label>Option:</label>
				<div class="form-group ">
					<div class="input-group">
						<div class="input-group-prepend">
							<a href="{% url 'choices:create' %}" target="_blank" class="input-group-text"><i class="flaticon-plus"></i></a>
						</div>
						{{form.option}}
						<div class="input-group-append">
							<button class="input-group-text" type="button" style="color:white;"><i class="flaticon-refresh"></i></button>
						</div>
					</div>
				</div>
				{% for item in form.option.errors %}
					<div class="invalid-feedback">{{item}}</div>
				{% endfor %}
				<span class="form-text text-muted">Enter list of choices</span>
			</div>
		</script>

		<script type="text/html" id="hbs-detail">
			<div class="col-lg-3">
			<label class="">Default:</label>
			<input hidden id="id_default_val" value={{form.default.value}}>
			<div class="form-group ">
				<div class="input-group">
					<div class="input-group-prepend">
						<a href="#" target="_blank" class="input-group-text"><i class="flaticon-plus"></i></a>
					</div>
					{{form.default}}
					<div class="input-group-append">
						<button class="input-group-text" type="button" style="color:white;"><i class="flaticon-refresh"></i></button>
					</div>
				</div>
			</div>
		</script>

		<script type="text/html" id="hbs-default">
			<div class="col-lg-3">
			<label class="">Default:</label>
			<input hidden id="id_default_val" value={{form.default.value}}>
			{{form.default}}
			{% for item in form.default.errors %}
				<div class="invalid-feedback">{{item}}</div>
			{% endfor %}
			<span class="form-text text-muted" id="id_default_helptext">Enter default value</span>
			</div>
		</script>

		<script type="text/html" id="hbs-maxlength">
			<div class="col-lg-3">
			<label>Max length:</label>
			{{form.max_length}}
			{% for item in form.max_length.errors %}
			<div class="invalid-feedback">{{item}}</div>
			{% endfor %}
			<span class="form-text text-muted">Field max length</span>
			</div>
		</script>

	</div>
</form>
{% endblock content %} {% block javascript %}
{% comment %}
<script type="text/javascript" src="{% static 'plugins/custom/datatables/datatables.bundle.js' %}"></script>
{% endcomment %}
<script type="text/javascript" src="{% static 'js/riso/app_mgmt/edit.js' %}"></script>
<script type="text/javascript" src="{% static 'js/riso/jquery.render.js' %}"></script>
{% endblock javascript %} {% block pagescript %}

<script>
	$(document).ready(function () {
		$('#id_module').val('{{model}}').prop('selected', true).change();
	});
</script>

{% endblock pagescript %}

risocrm/app_mgmt/templates/app_mgmt-list.html
{% extends 'base.html' %}
{% load static %}
{% block css %} {% endblock css %}
{% block pagecss %}
<link href="{% static 'plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" /> {% endblock pagecss %} 
{% block toolbar %} {% endblock toolbar %}
 {% block content %}
<div class="kt-portlet kt-portlet--mobile kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand {{st_icon}}"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                {{table_title}}
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-wrapper">
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">
        <!--begin: Datatable -->
        <div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row">
                <div class="col-sm-12">
                    <!--begin: Datatable -->
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>App Name</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for model in models %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{model}}</td>
                                <td>
                                    <a class="btn btn-sm btn-clean btn-icon btn-icon-md" title="View" href="{% url 'app_mgmt:view' %}?model={{model}}">
                                        <i class="la la-eye"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <!--end: Datatable -->
                </div>
            </div>
        </div>
        <!--end: Datatable -->
    </div>
</div>

{% endblock content %} {% block javascript %}
<script type="text/javascript" src="{% static 'plugins/custom/datatables/datatables.bundle.js' %}"></script>
<script type="text/javascript" src="{% static 'js/riso/app_mgmt/list.js' %}"></script>
<script type="text/javascript" src="{% static 'js/riso/datatable/html-table.js' %}"></script>
{% endblock javascript %} {% block pagescript %}
<script>
    $('#kt_table_1').risoHtmlTable({
    });
</script>

{% endblock pagescript %}

risocrm/app_mgmt/templates/app_mgmt-view.html
{% extends 'base.html' %}
{% load static %}
{% block css %} {% endblock css %}
{% block pagecss %}
<link href="{% static 'plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" /> {% endblock pagecss %} 
{% block toolbar %}

{% endblock toolbar %} {% block content %}
<div class="kt-portlet kt-portlet--mobile kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                {{table_title}}
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-wrapper">
                <div class="kt-portlet__head-actions">
                    &nbsp;
                    <a href="{% url 'app_mgmt:create' %}?model={{model}}" class="btn btn-success" data-toggle="kt-tooltip" data-placement="left" data-original-title="Create new">
                        <i class="la la-plus" style="padding-right: 0px;"></i>
                    </a>
                    &nbsp;
                    <a data-toggle="modal" data-target="#m_delete_multi" class="btn btn-danger"
                        style="color: white;">
                        <i class="la la-trash" style="padding-right: 0px;" data-toggle="kt-tooltip" data-placement="left" data-original-title="Delete"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">

        <!--begin: Datatable -->
        <div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row">
                <div class="col-sm-12">
                    <!--begin: Datatable -->
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>ID</th>
                                <th>Module</th>
                                <th>Group</th>
                                <th>Name</th>
                                <th>Verbose name</th>
                                <th>Type</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for obj in obj_list %}
                            <tr>
                                <td>{{ obj.id }}</td>
                                <td>{{ forloop.counter }}</td>
                                <td>{{obj.module|title}}</td>
                                <td>{{obj.group}}</td>
                                <td>{{obj.name}}</td>
                                <td>{{obj.verbose_name}}</td>
                                <td>{{obj.type}}</td>
                                <td>
                                {% if obj.is_base %}
                                <a class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Edit" href="{% url 'app_mgmt:edit' obj.id %}">
                                    <i class="la la-edit"></i>
                                </a>
                                {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    <!--end: Datatable -->
                </div>
            </div>
        </div>

        <!--end: Datatable -->
    </div>
</div>
{% url 'app_mgmt:delete' as delete_url %}
{% include 'modals/delete_multiple.html' with delete_url=delete_url %}
{% endblock content %} {% block javascript %}
<script type="text/javascript" src="{% static 'plugins/custom/datatables/datatables.bundle.js' %}"></script>
<script type="text/javascript" src="{% static 'js/riso/datatable/html-table.js' %}"></script>
{% endblock javascript %} {% block pagescript %}
<script>
    $('#kt_table_1').risoHtmlTable({
        rowGroup: {
            dataSrc: [2,3]
        },
    });
    $('[data-target="#m_delete_multi"]').on('click', function () {
        var selectedIds = dynamicTable.data('plugin_risoDynamicTable').getSelectedRow();
        $('#idlist').val(selectedIds);
    });
</script>

{% endblock pagescript %}