config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

setting_patterns = [
    path("apps/", include("risocrm.app_mgmt.urls")),
    path("filters/", include("risocrm.filters.urls")),
    path("choices/", include("risocrm.choices.urls")),
    # path("menus/", include("risocrm.menus.urls")),
    path("notices/", include("risocrm.notices.urls")),
    path("configs/", include("risocrm.configs.urls")),
]

urlpatterns = [
    path("", include("risocrm.dashboard.urls")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("risocrm.users.urls", namespace="users")),

    # System
    path("settings/", include(setting_patterns)),
    path("accounts/", include("allauth.urls")),

    # NOTIFICATION
    path("webpush/", include("webpush.urls")),
    # Your stuff: custom urls includes go here
    # Contact management
    path("contacts/", include("risocrm.contacts.urls")),
    path("notes/", include("risocrm.notes.urls")),
    path("activities/", include("risocrm.activities.urls")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

# Automation adding app

risocrm/users/urls.py
"""
    App Router
    Staff Management
"""
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from risocrm.users.views import (create, delete, detail, index,
                                 user_redirect_view, view)
from risocrm.users.apis import UserViewSet
app_name = "users"

router = SimpleRouter(trailing_slash=False)
router.register(r"", UserViewSet)

fake_api = [
    path("", include(router.urls)),
]

urlpatterns = [
    path("~redirect/", user_redirect_view, name="redirect"),
    path('', index, name="list"),
    path('create', create, name="create"),
    path('delete', delete, name="delete"),
    path('api/', include(fake_api)),
    path("view/<str:username>/", view, name="view"),
    path("<str:username>/", detail, name="detail"),
]

risocrm/users/models.py
"""
    App Models
    Staff Management
"""
import datetime

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.cache import cache
from django.db.models import CASCADE, CharField, ForeignKey, ImageField
from django.urls import reverse


class User(AbstractUser):
    avatar = ImageField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    def group_verbose(self):
        GROUP = {
            'Administrator': 'danger',
            'Manager': 'warning',
            'Leader': 'success',
            'Sale': 'info',
        }
        try:
            group = self.groups.first().name
            return F'<span style="width: 100px;"><span class="btn btn-bold btn-sm btn-font-sm btn-label-{GROUP[group]}">{group}</span></span>'
        except Exception:
            return F'<span style="width: 100px;"><span class="btn btn-bold btn-sm btn-font-sm btn-label-danger">Non Group</span></span>'

    def active_verbose(self):
        if self.is_active:
            return '<span style="width: 100px;"><span class="btn btn-bold btn-sm btn-font-sm  btn-label-success">Active</span></span>'
        return '<span style="width: 100px;"><span class="btn btn-bold btn-sm btn-font-sm  btn-label-danger">Not Active</span></span>'

    def last_seen(self):
        return cache.get('seen_%s' % self.username)

    def online(self):
        if self.last_seen():
            now = datetime.datetime.now()
            if now > self.last_seen() + datetime.timedelta(
                    seconds=settings.USER_ONLINE_TIMEOUT):
                return False
            else:
                return True
        else:
            return False

    def online_verbose(self):
        if self.online:
            return '<span style="width: 100px;"><span class="btn btn-bold btn-sm btn-font-sm  btn-label-success">Online</span></span>'
        return '<span style="width: 100px;"><span class="btn btn-bold btn-sm btn-font-sm  btn-label-danger">Offline</span></span>'

    def is_subcribe(self):
        return self.webpush_info.all().count() > 0

risocrm/users/forms.py
"""
    App serializer
    Staff Management
"""
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.forms import CheckboxInput, ModelForm, Select, TextInput, formset_factory
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User
        fields = forms.UserCreationForm.Meta.fields + ('first_name', 'email', 'groups')

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = '__all__'

risocrm/users/views.py
"""
    App Controller
    Staff Management
"""
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.db import transaction
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView

from risocrm.bases.permissions import isSelfOrSuperOrDenie, roleAdministrator
from risocrm.users.forms import UserChangeForm, UserCreationForm, UserForm

User = get_user_model()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='/')
def index(request):
    context = {
        'page_title': 'Users',
        'table_title': 'User ist',
        'go_back_url': '',
        'go_back_desc': '',
        'obj_list': User.objects.all()
    }
    return render(request, 'users-list.html', context)


@login_required
def view(request, username):
    user_obj = get_object_or_404(User, username=username)
    context = {
        'page_title': 'Users',
        'table_title': F'Detail of {user_obj.first_name} {user_obj.username}',
        'go_back_url': reverse('users:list'),
        'go_back_desc': 'Users list',
        'user': user_obj,
        'form': UserForm(instance=user_obj)
    }
    return render(request, 'users-view.html', context)


@login_required
@user_passes_test(lambda u: u.is_superuser, login_url='/')
def create(request):
    context = {
        'page_title': 'Users',
        'table_title': 'Create new User',
        'go_back_url': reverse('users:list'),
        'go_back_desc': 'Users list'
    }
    if request.method == 'GET':
        form = UserCreationForm()
        context['form'] = form
        return render(request, 'users-create.html', context)
    else:
        form = UserCreationForm(request.POST)
        if not form.is_valid():
            context['form'] = form
            context['msg_error'] = "User form have error, please check again!"
            return render(request, 'users-create.html', context)
        else:
            user = form.save()
            if form.data['groups']:
                group = Group.objects.get(pk=form.data['groups'])
                user.groups.add(group)
            messages.add_message(request, messages.SUCCESS, 'Create new user success')
            return redirect('users:detail', user.username)


@login_required
@user_passes_test(isSelfOrSuperOrDenie)
def detail(request, username):
    try:
        referer = request.META.get('HTTP_REFERER')
        if 'socials' in referer:
            return redirect('socials:list')
    except Exception:
        pass

    user_obj = get_object_or_404(User, username=username)
    context = {
        'page_title': 'Users',
        'table_title': F'Update {user_obj.first_name} {user_obj.username}',
        'go_back_url': reverse('users:list'),
        'go_back_desc': 'Users list',
        'user': user_obj,
    }
    if request.method == 'GET':
        form = UserChangeForm(instance=user_obj)
        context['form'] = form
        return render(request, 'users-edit.html', context)
    else:
        form = UserChangeForm(request.POST, request.FILES, instance=user_obj)
        if not form.is_valid():
            context['form'] = form
            context['msg_error'] = "User form have error, please check again!"
            return render(request, 'users-edit.html', context)
        else:
            user = form.save()
            if not request.user.groups.filter(name='Administrator').exists():
                user.groups = user_obj.groups
                user.save()
            messages.add_message(request, messages.SUCCESS, F'Edit user {user.first_name} success')
            return redirect('users:detail', user.username)


@login_required
@user_passes_test(roleAdministrator, login_url='/')
def delete(request):
    if request.method == 'POST':
        del_list = request.POST.get('idlist')
        if del_list is not None:
            _del_list = [int(id) for id in del_list[:-1].split(',')]
            User.objects.filter(id__in=_del_list).delete()
    return redirect('users:list')

risocrm/users/templates/users-create.html
{% extends 'base.html' %}
{% load static %}
{% block css %} {% endblock css %}
{% block pagecss %}
<link href="{% static 'plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" /> {% endblock pagecss %} {% block toolbar %} {% endblock toolbar %} {% block content %}
<form action="{{request.path}}" method="post" class="validated">
     {% csrf_token %}
<div class="kt-portlet kt-portlet--mobile kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile">

    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand flaticon2-line-chart"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                {{table_title}}
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-wrapper">
                <div class="kt-portlet__head-actions">
                    &nbsp;
                    <button type="submit" class="btn btn-success">
                        <i class="la la-check" style="padding-right: 0px;"></i>
                    </button>
                    &nbsp;
                    <a href="{{go_back_url}}" class="btn btn-secondary">
                        <i class="la la-ban" style="padding-right: 0px;"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">

        <!--begin: Datatable -->
        <div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
    <div class="row">
        <div class="col-sm-12">
            <div class="kt-form kt-form--label-right">
                <div class="kt-portlet__body">
                    <div class="form-group row">
                        <div class="col-lg-4">
                            <label class="">Username:</label>
                            {{form.username}}
                            {% for item in form.username.errors %}
                            <div class="invalid-feedback">{{item}}</div>
                            {% endfor %}
                            <span class="form-text text-muted">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
                        </div>
                        <div class="col-lg-4">
                            <label class="">Full name:</label>
                            {{form.first_name}}
                            {% for item in form.first_name.errors %}
                            <div class="invalid-feedback">{{item}}</div>
                            {% endfor %}
                        </div>
                        <div class="col-lg-4">
                            <label class="">Email:</label>
                            {{form.email}}
                            {% for item in form.email.errors %}
                            <div class="invalid-feedback">{{item}}</div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-lg-4">
                            <label class="">Group:</label>
                            <select name="groups" id="id_groups" class="form-control kt-select2">
                                <option value="">---------</option>
                                <option value="1">Administrator</option>
                                <option value="2">Manager</option>
                                <option value="3">Leader</option>
                                <option value="4">Sale</option>
                            </select>
                            {% for item in form.groups.errors %}
                                <div class="invalid-feedback">{{item}}</div>
                            {% endfor %}
                        </div>
                        <div class="col-lg-4">
                            <label class="">Password:</label>
                            {{form.password1}}
                            {% for item in form.password1.errors %}
                            <div class="invalid-feedback">{{item}}</div>
                            {% endfor %}
                            <span class="form-text text-muted">Your password can't be too similar to your other personal information.</span>
                            <span class="form-text text-muted">Your password must contain at least 8 characters.</span>
                            <span class="form-text text-muted">Your password can't be a commonly used password.</span>
                            <span class="form-text text-muted">Your password can't be entirely numeric.</span>
                        </div>
                        <div class="col-lg-4">
                            <label class="">Password confirmation:</label>
                            {{form.password2}}
                            {% for item in form.password2.errors %}
                            <div class="invalid-feedback">{{item}}</div>
                            {% endfor %}
                            <span class="form-text text-muted">Enter the same password as before, for verification.</span>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>
        <!--end: Datatable -->
    </div>
</div>
<!--begin::Modal-->
</form>
{% endblock content %} {% block javascript %}
{% endblock javascript %} {% block pagescript %}
<script type="text/javascript" src="{% static 'js/riso/jquery.render.js' %}"></script>
{% endblock pagescript %}

risocrm/users/templates/users-edit.html
{% extends 'users-base.html' %}
{% load static %}
{% block user_content %}
<form method="POST" action="." id="userform" enctype="multipart/form-data">
{% csrf_token %}
<div class="row">
    <div class="col-xl-12">
        <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">Personal Information <small>update staff personal
                            informaiton</small></h3>
                </div>
                <div class="kt-portlet__head-toolbar">
                    <div class="kt-portlet__head-wrapper">
                        <div class="kt-portlet__head-actions">
                            &nbsp;
                            <button type="submit" class="btn btn-success">
                                <i class="la la-check" style="padding-right: 0px;"></i>
                            </button>
                            &nbsp;
                            <button type="reset" class="btn btn-secondary">
                                <i class="la la-refresh" style="padding-right: 0px;"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="kt-form kt-form--label-right" >
                
                <div class="kt-portlet__body">
                    <div class="kt-section kt-section--first">
                        <div class="kt-section__body validated">
                            <div class="row">
                                <label class="col-xl-3"></label>
                                <div class="col-lg-9 col-xl-6">
                                    <h3 class="kt-section__title kt-section__title-sm">Staff Info:</h3>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3 col-lg-3 col-form-label">Avatar</label>
                                <div class="col-lg-9 col-xl-6">
                                    <div class="kt-avatar kt-avatar--outline" id="kt_user_avatar">
                                        <div class="kt-avatar__holder"
                                            style="background-image: url({% if user.avatar %}{{user.avatar.url}} {% else %} {% static 'media/users/300_1.jpg' %}{% endif %})">
                                        </div>
                                        <label class="kt-avatar__upload" data-toggle="kt-tooltip" title=""
                                            data-original-title="Change avatar">
                                            <i class="fa fa-pen"></i>
                                            <input type="file" name="avatar" id="id_avatar" accept=".png, .jpg, .jpeg">
                                        </label>
                                        <span class="kt-avatar__cancel" data-toggle="kt-tooltip" title=""
                                            data-original-title="Cancel avatar">
                                            <i class="fa fa-times"></i>
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row d-none">
                                <label class="col-xl-3 col-lg-3 col-form-label">Username</label>
                                <div class="col-lg-9 col-xl-6">
                                    <input class="form-control" type="text" value="{{user.username}}" name="username"
                                        id="id_username">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3 col-lg-3 col-form-label">Name</label>
                                <div class="col-lg-9 col-xl-6">
                                    <input class="form-control" type="text" value="{{user.first_name}}"
                                        name="first_name" id="id_first_name">
                                    {% for item in form.first_name.errors %}
                                    <div class="invalid-feedback">{{item}}</div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-group row {% if request.user.groups.all.0.id > 1 %}d-none{% endif %} ">
                                <label class="col-xl-3 col-lg-3 col-form-label">Group</label>
                                <div class="col-lg-9 col-xl-6">
                                    <select name="groups" id="id_groups" class="form-control kt-select2">
                                        <option value="">---------</option>
                                        <option value="1" {% if user.groups.all.0.id == 1 %}selected{% endif %}>
                                            Administrator</option>
                                        <option value="2" {% if user.groups.all.0.id == 2 %}selected{% endif %}>Manager
                                        </option>
                                        <option value="3" {% if user.groups.all.0.id == 3 %}selected{% endif %}>Leader
                                        </option>
                                        <option value="4" {% if user.groups.all.0.id == 4 %}selected{% endif %}>Sale
                                        </option>
                                    </select>
                                    {% for item in form.groups.errors %}
                                    <div class="invalid-feedback">{{item}}</div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="form-group row d-none">
                                <label class="col-xl-3 col-lg-3 col-form-label">Email Address</label>
                                <div class="col-lg-9 col-xl-6">
                                    <div class="input-group">
                                        <div class="input-group-prepend"><span class="input-group-text"><i
                                                    class="la la-at"></i></span></div>
                                        <input type="email" class="form-control" value="{{form.email.value}}"
                                            id="id_email" name="email" placeholder="Email"
                                            aria-describedby="basic-addon1">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xl-3"></label>
                                <div class="col-lg-9 col-xl-6">
                                    <h3 class="kt-section__title kt-section__title-sm">System Info:</h3>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-3">
                                    <div class="d-none">
                                        <label>Date Joined:</label> {{form.date_joined}}</div>
                                </div>
                                <div class="col-lg-3">
                                    {% if request.user.is_superuser %}
                                    <label>Is Superuser:</label> {{form.is_superuser}}
                                    {% endif %}
                                </div>

                                <div class="col-lg-3">
                                    <label>Is Staff:</label> {{form.is_staff}}
                                </div>
                                <div class="col-lg-3">
                                    <label class="">Is Active:</label> {{form.is_active}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</form>
{% endblock user_content %}
{% block pagescript %}
<script type="text/javascript" src="{% static 'js/riso/jquery.render.js' %}"></script>
{% endblock pagescript %}

risocrm/users/templates/users-list.html
{% extends 'base.html' %}
{% load static %}
{% block css %} {% endblock css %}
{% block pagecss %}
<link href="{% static 'plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" />
{% endblock pagecss %} {% block toolbar %} {% endblock toolbar %} {% block content %}
<div class="kt-portlet kt-portlet--mobile kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand flaticon2-line-chart"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                {{table_title}}
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-wrapper">
                <div class="kt-portlet__head-actions">
                    &nbsp;
                    <a href="{% url 'users:create' %}" class="btn btn-success" data-toggle="kt-tooltip" data-placement="left" data-original-title="Create new">
                        <i class="la la-plus" style="padding-right: 0px;"></i>
                    </a>
                    {% if request.user.is_superuser %}
                    &nbsp;
                    <a data-toggle="modal" data-target="#m_delete_multi" class="btn btn-danger"
                        style="color: white;">
                        <i class="la la-trash" style="padding-right: 0px;" data-toggle="kt-tooltip" data-placement="left" data-original-title="Delete"></i>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">

        <!--begin: Datatable -->
        <div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row">
                <div class="col-sm-12">
                    <!--begin: Datatable -->
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
                    <thead>
                            <tr>
                                <th>Order ID</th>
                                <th>ID</th>
                                <th>Avatar</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Name</th>
                                <th>Group</th>
                                <th>Is Active</th>
                                <th>Is Online</th>
                                <th>Last seen</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        {% for obj in obj_list %}
                            <tr>
                                <td>{{obj.id}}</td>
                                <td>{{ forloop.counter }}</td>
                                <td>
                                 <div class="kt-user-card-v2">
                                    <div class="kt-user-card-v2__pic">
                                        <img src="{% if obj.avatar %}{{obj.avatar.url}} {% else %} {% static 'media/users/300_1.jpg' %}{% endif %}" class="m-img-rounded kt-marginless" alt="photo">
                                    </div>
                                </div>
                                </td>
                                <td>{{obj.username}}</td>
                                <td>{{obj.email}}</td>
                                <td>{{obj.first_name}}</td>
                                <td>{{obj.group_verbose|safe}}</td>
                                <td>{{obj.active_verbose|safe}}</td>
                                <td>{{obj.online_verbose|safe}}</td>
                                <td>
                                    {{obj.last_seen}}
                                </td>
                                <td>
                                <a class="btn btn-sm btn-clean btn-icon btn-icon-md" title="View" href="{% url 'users:view' obj.username %}">
                                    <i class="la la-eye"></i>
                                </a>
                                <a class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Edit" href="{% url 'users:detail' obj.username %}">
                                    <i class="la la-edit"></i>
                                </a>
                                </td>
                            </tr>
                            
                        {% endfor %}
                    </table>

                    <!--end: Datatable -->
                </div>
            </div>
        </div>

        <!--end: Datatable -->
    </div>
</div>
<!--begin::Modal-->

{% url 'users:delete' as delete_url %}
{% include 'modals/delete_multiple.html' with delete_url=delete_url %}
{% endblock content %} {% block javascript %}
<script type="text/javascript" src="{% static 'plugins/custom/datatables/datatables.bundle.js' %}"></script>
<script type="text/javascript" src="{% static 'js/riso/datatable/html-table.js' %}"></script>
{% endblock javascript %} {% block pagescript %}
<script>
    var dynamicTable = $('#kt_table_1').risoHtmlTable();
    $('[data-target="#m_delete_multi"]').on('click', function () {
        var selectedIds = dynamicTable.data('plugin_risoDynamicTable').getSelectedRow();
        $('#idlist').val(selectedIds);
    });
</script>

{% endblock pagescript %}