config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

setting_patterns = [
    path("apps/", include("risocrm.app_mgmt.urls")),
    path("filters/", include("risocrm.filters.urls")),
    path("choices/", include("risocrm.choices.urls")),
    # path("menus/", include("risocrm.menus.urls")),
    path("notices/", include("risocrm.notices.urls")),
    path("configs/", include("risocrm.configs.urls")),
]

urlpatterns = [
    path("", include("risocrm.dashboard.urls")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("risocrm.users.urls", namespace="users")),

    # System
    path("settings/", include(setting_patterns)),
    path("accounts/", include("allauth.urls")),

    # NOTIFICATION
    path("webpush/", include("webpush.urls")),
    # Your stuff: custom urls includes go here
    # Contact management
    path("contacts/", include("risocrm.contacts.urls")),
    path("notes/", include("risocrm.notes.urls")),
    path("activities/", include("risocrm.activities.urls")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

# Automation adding app

risocrm/choices/urls.py
"""
    App Urls
    Filters Router
"""
from django.urls import include, path

from risocrm.choices.apis import choice_childs, choice_list
from risocrm.choices.views import create, delete, edit, index, view

app_name = 'choices'


fake_api = [
    path('choice_list', choice_list, name="choice_list"),
    path('choice_childs/<str:pk>', choice_childs, name="choice_childs"),
]

urlpatterns = [
    path('api/', include(fake_api)),
    path('', index, name="list"),
    path('create', create, name="create"),
    path('delete', delete, name="delete"),
    path("view/<str:pk>/", view, name="view"),
    path('<str:pk>', edit, name="edit"),
]

risocrm/choices/models.py
"""
    App Models
    Choice model
"""
from django.db.models import CASCADE, CharField, ForeignKey, Model

from risocrm.bases.models import BaseModel


class Choice(BaseModel):
    """
        Choice
    """
    name = CharField(default="", max_length=50, )

    def __str__(self):
        return F"Choice {self.name}"

    def detail_counter(self):
        return self.choices_detail.all().count()


class ChoiceDetail(Model):
    choice = ForeignKey(Choice, related_name="choices_detail", on_delete=CASCADE)
    value = CharField(max_length=250)

    def __str__(self):
        return F"{self.value}"

risocrm/choices/forms.py
"""
    App serializer
    Choice serializer
"""

from django.forms import ModelForm, inlineformset_factory

from risocrm.choices.models import Choice, ChoiceDetail


class ChoiceForm(ModelForm):

    class Meta:
        model = Choice
        fields = '__all__'


class ChoiceDetailForm(ModelForm):
    class Meta:
        model = ChoiceDetail
        fields = '__all__'


ChoiceDetailFS = inlineformset_factory(Choice, ChoiceDetail, form=ChoiceDetailForm, extra=1)

risocrm/choices/views.py
"""
    App Controller
    Choices Management
"""

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from risocrm.choices.forms import ChoiceDetailFS, ChoiceForm
from risocrm.choices.models import Choice

User = get_user_model()


@login_required
def index(request):
    context = {
        'page_title': 'Choices',
        'table_title': 'List',
        'go_back_url': '',
        'go_back_desc': '',
        'obj_list': Choice.objects.all()
    }
    return render(request, 'choices-list.html', context)


@login_required
def view(request, pk):
    obj = get_object_or_404(Choice, pk=pk)
    context = {
        'page_title': 'Choices',
        'table_title': F'Detail {obj.name}',
        'go_back_url': reverse('choices:list'),
        'go_back_desc': 'Choices list',
        'obj': obj,
        'choices': obj.choices_detail.all()
    }
    return render(request, 'choices-view.html', context)


@login_required
def create(request):
    context = {
        'page_title': 'Choices',
        'table_title': 'Create new Choice',
        'go_back_url': reverse('choices:list'),
        'go_back_desc': 'Choices list'
    }
    _choice = Choice()
    if request.method == 'GET':
        context['form'] = ChoiceForm()
        context['formset'] = ChoiceDetailFS(instance=_choice)
        return render(request, 'choices-edit.html', context)
    else:
        form = ChoiceForm(request.POST)
        if not form.is_valid():
            context['form'] = form
            context['formset'] = ChoiceDetailFS(request.POST, instance=_choice)
            context['msg_error'] = "Choice form have error, please check again!"
            return render(request, 'choices-edit.html', context)
        else:
            choice = form.save(commit=False)
            formset = ChoiceDetailFS(request.POST, instance=choice)
            for _form in formset:
                if not _form.is_valid():
                    context['form'] = form
                    context['formset'] = ChoiceDetailFS(request.POST, instance=_choice)
                    context['msg_error'] = "Detail form have error, please check again!"
                    return render(request, 'choices-edit.html', context)
            with transaction.atomic():
                choice.creator = request.user
                choice.save()
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Create new choice success')
                return redirect('choices:edit', choice.id)


@login_required
def edit(request, pk):
    choice_obj = get_object_or_404(Choice, pk=pk)
    context = {
        'page_title': 'Choices',
        'table_title': F'Update {choice_obj.name}',
        'go_back_url': reverse('choices:list'),
        'go_back_desc': 'Choices list',
        'choice': choice_obj,
    }
    if request.method == 'GET':
        context['form'] = ChoiceForm(instance=choice_obj)
        context['formset'] = ChoiceDetailFS(instance=choice_obj)
        return render(request, 'choices-edit.html', context)
    else:
        form = ChoiceForm(request.POST, instance=choice_obj)
        if not form.is_valid():
            context['form'] = form
            context['formset'] = ChoiceDetailFS(request.POST, instance=choice_obj)
            context['msg_error'] = "Form have error, please check again!"
            return render(request, 'choices-edit.html', context)
        else:
            formset = ChoiceDetailFS(request.POST, instance=choice_obj)
            if not formset.is_valid():
                context['form'] = form
                context['formset'] = ChoiceDetailFS(request.POST, instance=choice_obj)
                context['msg_error'] = "Formset have error, please check again!"
                return render(request, 'choices-edit.html', context)
            else:
                choice = form.save(commit=False)
                choice.last_modified_by = request.user
                choice.save()
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Create new tile success')
                return redirect('choices:edit', choice.id)


@login_required
def delete(request):
    if request.method == 'POST':
        del_list = request.POST.get('idlist')
        if del_list is not None:
            _del_list = [id for id in del_list[:-1].split(',')]
            Choice.objects.choice(id__in=_del_list).delete()
    return redirect('choices:list')

risocrm/choices/templates/choices-edit.html
{% extends 'base.html' %}
{% load static %}
{% block css %} {% endblock css %}
{% block pagecss %}
<link href="{% static 'plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" /> {% endblock pagecss %} {% block toolbar %} {% endblock toolbar %} {% block content %}
<form action="{{request.path}}" method="post" class="validated">
     {% csrf_token %}
  <div class="kt-portlet kt-portlet--mobile kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand flaticon2-line-chart"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                {{table_title}}
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-wrapper">
                <div class="kt-portlet__head-actions">
                    &nbsp;
                    <button type="submit" class="btn btn-success">
                        <i class="la la-check" style="padding-right: 0px;"></i>
                    </button>
                    &nbsp;
                    <a href="{{go_back_url}}" class="btn btn-secondary">
                        <i class="la la-ban" style="padding-right: 0px;"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">

        <!--begin: Datatable -->
        <div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row">
                <div class="col-sm-12">
                    <div class="kt-form kt-form--label-right">
                      <div class="kt-portlet__body ">
                        <div class="form-group row">
                            <div class="col-lg-3 d-none">
                            {{form.creator}}
                            {{form.last_modified_by}}
                            </div>
                            <div class="col-lg-10">
                                <label>Name:</label>
                                {{form.name}}
                                {% for item in form.name.errors %}
                                <div class="invalid-feedback">{{item}}</div>
                                {% endfor %}
                                <span class="form-text text-muted">Please enter Choice name</span>
                            </div>
                        </div>
                      </div>
                    </div>
                </div>
                <div class="col-sm-12">
                <h5>Values</h5>
                <div class="kt-form kt-form--label-right contain_form">
                    {{ formset.management_form }}
                    <div class="kt-portlet__body detailformsetdiv">
                      {% for dtform in formset %}
                      {{dtform.id}}
                      <div class="form-group row validated rowDetail-{{forloop.counter0}}">
                        <div class="col-lg-10">
                          <label class="form-control-label">Value:</label>
                          {{dtform.value}}
                          {% for item in dtform.value.errors %}
                          <div class="invalid-feedback">{{item}}</div>
                          {% endfor %}
                          <span class="form-text text-muted">Enter value</span>
                        </div>
                        <div class="col-lg-2">
                          <label class="">Delete</label><br/>
                            <label data-item="{{forloop.counter0}}"
                              class="btn-delete-item btn btn-danger btn-icon">
                              <i class="fa flaticon-delete-2"></i>
                              <span hidden>{{dtform.DELETE}}</span>
                        </label>
                        </div>
                      </div>
                      {% endfor %}

                    </div>
                    <div class="kt-portlet__foot">
                      <div class="row align-items-center">
                        <div class="nullDivDetail col-lg-6 m--valign-middle" style="display:none">
                          <div class="form-group row validated rowDetail-__prefix__">
                            {{formset.empty_form.id}}
                            <div class="col-lg-10">
                              <label>Value:</label>
                              {{formset.empty_form.value}}
                              {% for item in form.value.errors %}
                              <div class="invalid-feedback">{{item}}</div>
                              {% endfor %}
                              <span class="form-text text-muted">Enter value</span>
                            </div>
                            <div class="col-lg-2">
                              <label class="">Delete</label><br/>
                                <label data-item="__prefix__"
                                  class="btn-delete-item btn btn-danger btn-icon">
                                  <i class="fa flaticon-delete-2"></i>
                                  <span hidden>{{form.DELETE}}</span>
                            </label>
                            </div>
                          </div>
                        </div>
                        <div class="col-lg-6 kt-align-right">
                          <a class="addBtnDetailFS btn btn-outline-success btn-sm btn-icon btn-icon-md">
                            <i class="flaticon2-add-1"></i>
                          </a>
                        </div>
                      </div>
                    </div>
                </div>

            </div>
        </div>

        <!--end: Datatable -->
    </div>
  </div>
</form>
<!--begin::Modal-->

{% endblock content %} {% block javascript %}
<script type="text/javascript" src="{% static 'js/riso/dynamic-formset.js' %}"></script>
{% endblock javascript %} {% block pagescript %}
<script>
  deleteFormSet();
  addFormSet();
</script>

{% endblock pagescript %}

risocrm/choices/templates/choices-list.html
{% extends 'base.html' %}
{% load static %}
{% block css %} {% endblock css %}
{% block pagecss %}
<link href="{% static 'plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" /> {% endblock pagecss %} {% block toolbar %} {% endblock toolbar %} {% block content %}
<div class="kt-portlet kt-portlet--mobile kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand flaticon2-line-chart"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                {{table_title}}
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-wrapper">
                <div class="kt-portlet__head-actions">
                    &nbsp;
                    <a href="{% url 'choices:create' %}" class="btn btn-success" data-toggle="kt-tooltip" data-placement="left" data-original-title="Create new">
                        <i class="la la-plus" style="padding-right: 0px;"></i>
                    </a>
                    &nbsp;
                    <a data-toggle="modal" data-target="#m_delete_multi" class="btn btn-danger" style="color: white;">
                        <i class="la la-trash" style="padding-right: 0px;" data-toggle="kt-tooltip" data-placement="left" data-original-title="Delete"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">

        <!--begin: Datatable -->
        <div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row">
                <div class="col-sm-12">
                    <!--begin: Datatable -->
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
                    <thead>
                            <tr>
                                <th>Order ID</th>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Choice count</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        {% for obj in obj_list %}
                            <tr>
                                <td>{{obj.id}}</td>
                                <td>{{ forloop.counter }}</td>
                                <td>{{obj.name}}</td>
                                <td>{{obj.detail_counter}}</td>
                                <td>
                                <a class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Edit" href="{% url 'choices:view' obj.id %}">
                                    <i class="la la-eye"></i>
                                </a>
                                <a class="btn btn-sm btn-clean btn-icon btn-icon-md" title="Edit" href="{% url 'choices:edit' obj.id %}">
                                    <i class="la la-edit"></i>
                                </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>

                    <!--end: Datatable -->
                </div>
            </div>
        </div>

        <!--end: Datatable -->
    </div>
</div>
<!--begin::Modal-->

{% url 'choices:delete' as delete_url %}
{% include 'modals/delete_multiple.html' with delete_url=delete_url %}
{% endblock content %} {% block javascript %}
<script type="text/javascript" src="{% static 'plugins/custom/datatables/datatables.bundle.js' %}"></script>
<script type="text/javascript" src="{% static 'js/riso/datatable/html-table.js' %}"></script>
{% endblock javascript %} {% block pagescript %}
<script>
    $('#kt_table_1').risoHtmlTable();
    $('[data-target="#m_delete_multi"]').on('click', function () {
        var selectedIds = dynamicTable.data('plugin_risoDynamicTable').getSelectedRow();
        $('#idlist').val(selectedIds);
    });
</script>

{% endblock pagescript %}

risocrm/choices/templates/choices-view.html
{% extends 'base.html' %}
{% load static %}
{% block css %} {% endblock css %}
{% block pagecss %}
<link href="{% static 'plugins/custom/datatables/datatables.bundle.css' %}" rel="stylesheet" type="text/css" /> {% endblock pagecss %} {% block toolbar %} {% endblock toolbar %} {% block content %}
<div class="kt-portlet kt-portlet--mobile kt-portlet--last kt-portlet--head-lg kt-portlet--responsive-mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand flaticon2-line-chart"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                {{table_title}}
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <div class="kt-portlet__head-wrapper">
                <div class="kt-portlet__head-actions">
                    &nbsp;
                    <a href="{% url 'choices:edit' obj.id %}" class="btn btn-brand btn-elevate btn-icon-sm">
                        <i class="la la-plus"></i> Edit
                    </a>
                    &nbsp;
                    <a data-toggle="modal" data-target="#m_delete_multi" class="btn btn-danger btn-elevate btn-icon-sm" style="color: white;">
                        <i class="la la-trash"></i> Delete
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="kt-portlet__body">

        <!--begin: Datatable -->
        <div id="kt_table_1_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
            <div class="row">
                <div class="col-sm-12">
                    <!--begin: Datatable -->
                    <table class="table table-striped- table-bordered table-hover table-checkable" id="kt_table_1">
                    <thead>
                            <tr>
                                <th>Order ID</th>
                                <th>ID</th>
                                <th>Choice</th>
                                <th>Value</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        {% for choice in choices %}
                            <tr>
                                <td>{{choice.id}}</td>
                                <td>{{ forloop.counter }}</td>
                                <td>{{choice.choice.name}}</td>
                                <td>{{choice.value}}</td>
                                <td>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                    <!--end: Datatable -->
                </div>
            </div>
        </div>
        <!--end: Datatable -->
    </div>
</div>
<!--begin::Modal-->

{% url 'choices:delete' as delete_url %}
{% include 'modals/delete_multiple.html' with delete_url=delete_url %}
{% endblock content %} {% block javascript %}
<script type="text/javascript" src="{% static 'plugins/custom/datatables/datatables.bundle.js' %}"></script>
<script type="text/javascript" src="{% static 'js/riso/datatable/html-table.js' %}"></script>
{% endblock javascript %} {% block pagescript %}
<script>
    $('#kt_table_1').risoHtmlTable({
        rowGroup: {
            dataSrc: [2,]
        },
    });
    $('[data-target="#m_delete_multi"]').on('click', function () {
        $('#idlist').val("{{obj.id}}");
    });
</script>

{% endblock pagescript %}