config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

setting_patterns = [
    path("apps/", include("risocrm.app_mgmt.urls")),
    path("filters/", include("risocrm.filters.urls")),
    path("choices/", include("risocrm.choices.urls")),
    # path("menus/", include("risocrm.menus.urls")),
    path("notices/", include("risocrm.notices.urls")),
    path("configs/", include("risocrm.configs.urls")),
]

urlpatterns = [
    path("", include("risocrm.dashboard.urls")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("risocrm.users.urls", namespace="users")),

    # System
    path("settings/", include(setting_patterns)),
    path("accounts/", include("allauth.urls")),

    # NOTIFICATION
    path("webpush/", include("webpush.urls")),
    # Your stuff: custom urls includes go here
    # Contact management
    path("contacts/", include("risocrm.contacts.urls")),
    path("notes/", include("risocrm.notes.urls")),
    path("activities/", include("risocrm.activities.urls")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

# Automation adding app

risocrm/app_mgmt/urls.py
"""
    App Urls
    App Management
"""
from django.urls import include, path

from risocrm.app_mgmt.apis import (get_field, get_field_label, get_field_type,
                                   get_foreign_data, get_label, get_module,
                                   make_migrations, migrate)
from risocrm.app_mgmt.views import create, delete, edit, index, view

app_name = 'app_mgmt'

fake_api = [
    path('make_migrations', make_migrations, name="make_migrations"),
    path('migrate', migrate, name="migrate"),
    path('get_module', get_module, name="get_module"),
    path('get_label', get_label, name="get_label"),
    path('get_field', get_field, name="get_field"),
    path('get_field_type', get_field_type, name="get_field_type"),
    path('get_foreign_data', get_foreign_data, name="get_foreign_data"),
    path('get_field_label', get_field_label, name="get_field_label"),
]

urlpatterns = [
    path("", index, name="index"),
    path("view", view, name="view"),
    path("create", create, name="create"),
    path('delete', delete, name="delete"),
    path("api/", include(fake_api)),
    path('<str:pk>', edit, name="edit"),
]

risocrm/choices/urls.py
"""
    App Urls
    Filters Router
"""
from django.urls import include, path

from risocrm.choices.apis import choice_childs, choice_list
from risocrm.choices.views import create, delete, edit, index, view

app_name = 'choices'


fake_api = [
    path('choice_list', choice_list, name="choice_list"),
    path('choice_childs/<str:pk>', choice_childs, name="choice_childs"),
]

urlpatterns = [
    path('api/', include(fake_api)),
    path('', index, name="list"),
    path('create', create, name="create"),
    path('delete', delete, name="delete"),
    path("view/<str:pk>/", view, name="view"),
    path('<str:pk>', edit, name="edit"),
]

risocrm/contacts/urls.py
"""
    App Router
    Contacts Router
"""
from django.urls import include, path
from rest_framework.routers import SimpleRouter
from risocrm.contacts.apis import ContactViewSet
from risocrm.contacts.views import index, create, edit, delete, view, importcontacts, exportcontacts

app_name = 'contacts'

router = SimpleRouter(trailing_slash=False)
router.register(r"", ContactViewSet, basename="contacts")

urlpatterns = [
    path('', index, name="list"),
    path('create', create, name="create"),
    path('view/<str:pk>', view, name="view"),
    path('delete', delete, name="delete"),
    path('import', importcontacts, name="import"),
    path('export', exportcontacts, name="export"),
    path('api/', include(router.urls)),
    path('<str:pk>', edit, name="edit"),
]

risocrm/dashboard/urls.py
"""
    App Router
    Dashboard Management
"""
from django.urls import include, path
from rest_framework.routers import SimpleRouter
from risocrm.dashboard.views import index, delete, create, edit, dashboard

app_name = 'dashboard'

# router = SimpleRouter(trailing_slash=False)
# router.register(r"", MenuViewSet)

# fake_api = [
#     path('get_group', get_group, name="get_group"),
#     path('', include(router.urls)),
# ]

urlpatterns = [
    path('', dashboard, name="dashboard"),
    path('dashboard/list', index, name="list"),
    path('dashboard/create', create, name="create"),
    path('dashboard/delete', delete, name="delete"),
    # path('api/', include(fake_api)),
    path('dashboard/<str:pk>', edit, name="edit"),
]

risocrm/filters/urls.py
"""
    App Urls
    Filters Router
"""
from django.urls import path

from risocrm.filters.views import create, delete, edit, index

app_name = 'filters'

urlpatterns = [
    path('', index, name="list"),
    path('create', create, name="create"),
    path('delete', delete, name="delete"),
    path('<str:pk>', edit, name="edit"),
]

risocrm/notes/urls.py
"""
    App Router
    Note Router
"""
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from risocrm.notes.apis import NoteViewSet, create

app_name = 'notes'

router = SimpleRouter(trailing_slash=False)
router.register(r"", NoteViewSet)

fake_api = [
    path('create', create, name="create"),
    path('', include(router.urls)),
    
]

urlpatterns = [
    path("api/", include(fake_api)),
]

risocrm/users/urls.py
"""
    App Router
    Staff Management
"""
from django.urls import include, path
from rest_framework.routers import SimpleRouter

from risocrm.users.views import (create, delete, detail, index,
                                 user_redirect_view, view)
from risocrm.users.apis import UserViewSet
app_name = "users"

router = SimpleRouter(trailing_slash=False)
router.register(r"", UserViewSet)

fake_api = [
    path("", include(router.urls)),
]

urlpatterns = [
    path("~redirect/", user_redirect_view, name="redirect"),
    path('', index, name="list"),
    path('create', create, name="create"),
    path('delete', delete, name="delete"),
    path('api/', include(fake_api)),
    path("view/<str:username>/", view, name="view"),
    path("<str:username>/", detail, name="detail"),
]

risocrm/app_mgmt/forms.py
"""
    App Forms
    App Management
"""

from django.forms import (CheckboxInput, ModelForm, Select, TextInput,
                          inlineformset_factory, CharField)

from risocrm.app_mgmt.models import Dynafield


class DynafieldForm(ModelForm):

    class Meta:
        model = Dynafield
        fields = '__all__'
        widgets = {
            'type': Select(attrs={'class': 'form-control kt-select2'}),
            'module': Select(attrs={'class': 'form-control kt-select2'}),
            'fkmodule': Select(attrs={'class': 'form-control kt-select2'}),
            'group': Select(attrs={'class': 'form-control kt-select2'}),
            'option': Select(attrs={'class': 'form-control kt-select2'}),
            'default': Select(attrs={'class': 'form-control kt-select2'}),
        }

risocrm/bases/forms.py
"""
    Dynamic Form render
"""
from django.forms import (CheckboxInput, DateInput, DateTimeInput, FileField,
                          FileInput, Form, NumberInput, Select, SelectMultiple,
                          TextInput, TimeInput, modelform_factory)
from django.urls import reverse

from risocrm.app_mgmt.helpers import (get_field_distinct_list,
                                      get_group_distinct_list)
from risocrm.bases.fields import app_get_field_object
from risocrm.app_mgmt.models import Dynafield
from risocrm.bases.variables import (BOOL_TYPE, FILE_TYPE, NUMBER_TYPE,
                                            STRING_TYPE)

DATE_TYPE = ['DateField']
DATETIME_TYPE = ['DateTimeField']
TIME_TYPE = ['TimeField']
ONE_TYPE = ['ForeignKey', 'OneToOneField']
TWO_TYPE = ['ManyToManyField']


def get_type(model, name):
    _type = app_get_field_object(model, name)
    if _type.get_internal_type() in BOOL_TYPE:
        return CheckboxInput(attrs={'class': 'bool-field form-control'})

    if _type.get_internal_type() in FILE_TYPE:
        return FileInput(attrs={'class': 'file-field form-control'})

    if _type.get_internal_type() in NUMBER_TYPE:
        return NumberInput(attrs={'class': 'number-field form-control'})

    if _type.get_internal_type() in ONE_TYPE:
        related_model = _type.related_model.__module__.split(".")[1]
        if related_model == 'choices':
            _field = Dynafield.objects.filter(module=model).filter(name=name).first()
            url = reverse(F'{related_model}:edit', kwargs={'pk': _field.option.id})
            refresh_url = reverse(F'{_type.related_model.__module__.split(".")[1]}:choice_childs', kwargs={'pk': _field.option.id})
        else:
            url = reverse(F'{related_model}:create')
            refresh_url = reverse(F'{_type.related_model.__module__.split(".")[1]}:create')
        return Select(attrs={'class': 'relation-field form-control kt-select2', 'fk':name, 'created': url, 'refresh': refresh_url})

    if _type.get_internal_type() in TWO_TYPE:
        url = reverse(F'{_type.related_model.__module__.split(".")[1]}:create')
        refresh_url = reverse(F'{_type.related_model.__module__.split(".")[1]}:create')
        return SelectMultiple(attrs={'class': 'relation-field form-control kt-select2', 'fk':name, 'created': url, 'refresh': refresh_url})

    if _type.get_internal_type() in STRING_TYPE:
        return TextInput(attrs={'class': 'string-field form-control'})

    if _type.get_internal_type() in DATE_TYPE:
        return DateInput(attrs={'class': 'date-field form-control', 'placeholder': 'Select date'})

    if _type.get_internal_type() in DATETIME_TYPE:
        return DateTimeInput(attrs={'class': 'datetime-field form-control', 'placeholder': 'Select date & time'})

    if _type.get_internal_type() in TIME_TYPE:
        return TimeInput(attrs={'class': 'time-field form-control', 'placeholder': 'Select time'})

    return TextInput()


def DynoForm(model, module):
    groups = get_group_distinct_list(model)
    hidden_fields = [
        'creator',
        'last_modified_by']
    forms = [
        {
            'group': 'Hidden',
            'form': modelform_factory(
                module,
                fields=hidden_fields,
                widgets={
                    'creator': TextInput(attrs={'class': 'd-none'}),
                    'last_modified_by': TextInput(attrs={'class': 'd-none'})
                }
            )
        }
    ]
    for group in groups:
        fields = get_field_distinct_list(model, group)
        widgets = {name: get_type(model, name) for name in fields}
        forms.append(
            {
                'group': group,
                'form': modelform_factory(module, fields=fields, widgets=widgets)
            }
        )
    return forms


class ImportForm(Form):
    file = FileField()

risocrm/app_mgmt/views.py
"""
    App Controller
    App Management
"""
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from risocrm.app_mgmt.forms import DynafieldForm
from risocrm.app_mgmt.helpers import get_group_distinct_tuple, model_render
from risocrm.app_mgmt.models import Dynafield
from risocrm.bases.apps import app_name_tuple, app_name_list
from risocrm.bases.variables import ADDED_APP, BASE_MODEL


@login_required()
def index(request):
    """
        Return all model on project
    """
    content = {
        'page_title': 'App Mangement',
        'table_title': 'Model list',
        'go_back_url': '',
        'go_back_desc': '',
    }
    model_list = app_name_list()
    # Remove Module of System
    content['models'] = list(set(model_list) ^ set(BASE_MODEL + ADDED_APP))

    return render(request, 'app_mgmt-list.html', content)


@login_required()
def view(request):
    """
        View detail field of 1 model
        Input is request parameter ?model=
    """
    model = request.GET.get("model", None)
    if not model:
        return redirect('app_mgmt:index')

    content = {
        'page_title': 'App Management',
        'table_title': 'List field of module' + model,
        'go_back_url': reverse('app_mgmt:index'),
        'go_back_desc': 'Model list',
        'model': model,
    }
    content['obj_list'] = Dynafield.objects.filter(module=model).order_by('group')

    return render(request, 'app_mgmt-view.html', content)


@login_required
def create(request):
    model = request.GET.get("model", "")
    context = {
        'page_title': 'App Mangement',
        'table_title': 'Create new field',
        'go_back_url': reverse('app_mgmt:index'),
        'go_back_desc': 'Model list',
        'model': model
    }

    if request.method == 'GET':
        form = DynafieldForm()
        form.fields['group'].widget.choices = [('', '----------')] + get_group_distinct_tuple(model)
        form.fields['module'].widget.choices = [('', '----------')] + app_name_tuple()
        form.fields['fkmodule'].widget.choices = [('', '----------')] + app_name_tuple()
        context['form'] = form
        return render(request, 'app_mgmt-edit.html', context)
    else:
        form = DynafieldForm(request.POST)
        form.fields['group'].widget.choices = [('', '----------')] + get_group_distinct_tuple(model)
        form.fields['module'].widget.choices = [('', '----------')] + app_name_tuple()
        form.fields['fkmodule'].widget.choices = [('', '----------')] + app_name_tuple()
        if not form.is_valid():
            context['form'] = form
            context['msg_error'] = "Dynafield form have error, please check again!"
            return render(request, 'app_mgmt-edit.html', context)
        else:
            menu = form.save(commit=False)
            menu.creator = request.user
            menu.save()
            model_render(menu.module, Dynafield.objects.filter(module=menu.module))
            messages.add_message(request, messages.SUCCESS, 'Create new field success')
            return redirect('app_mgmt:edit', menu.id)


@login_required
def edit(request, pk):
    obj = get_object_or_404(Dynafield, pk=pk)
    context = {
        'page_title': 'Dynafields',
        'table_title': F'Update {obj.name}',
        'go_back_url': F"{reverse('app_mgmt:view')}?model={obj.module}",
        'go_back_desc': 'Dynafields list',
        'menu': obj,
        'model': obj.module
    }

    if request.method == 'GET':
        form = DynafieldForm(instance=obj)
        form.fields['group'].widget.choices = [('', '----------')] + get_group_distinct_tuple()
        form.fields['module'].widget.choices = [('', '----------')] + app_name_tuple()
        form.fields['fkmodule'].widget.choices = [('', '----------')] + app_name_tuple()
        if obj.option:
            form.fields['default'].widget.choices = [('', '----------')] + [(m.id, m.value)
                                                                            for m in obj.option.choices_detail.all()]
        context['form'] = form
        return render(request, 'app_mgmt-edit.html', context)
    else:
        form = DynafieldForm(request.POST, instance=obj)
        form.fields['group'].widget.choices = [('', '----------')] + get_group_distinct_tuple()
        form.fields['module'].widget.choices = [('', '----------')] + app_name_tuple()
        form.fields['fkmodule'].widget.choices = [('', '----------')] + app_name_tuple()
        if obj.option:
            form.fields['default'].widget.choices = [('', '----------')] + [(m.id, m.value)
                                                                            for m in obj.option.choices_detail.all()]
        if not form.is_valid():
            context['form'] = form
            return render(request, 'app_mgmt-edit.html', context)
        else:
            menu = form.save()
            menu.last_modified_by = request.user
            menu.save()
            model_render(obj.module, Dynafield.objects.filter(module=obj.module))
            messages.add_message(request, messages.SUCCESS, 'Update field success')
            return redirect('app_mgmt:edit', menu.id)


@login_required
def delete(request):
    if request.method == 'POST':
        del_list = request.POST.get('idlist')
        if del_list is not None:
            _del_list = [int(id) for id in del_list[:-1].split(',')]
            for field in _del_list:
                try:
                    obj = Dynafield.objects.get(pk=field)
                    model_render(obj.module, Dynafield.objects.filter(module=obj.module))
                    obj.delete()
                except Exception:
                    raise Http404
    return redirect('app_mgmt:index')

risocrm/templates/partials/menus/aside_menu.html
{% load static i18n %}

<div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
    <div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1" data-ktmenu-dropdown-timeout="500">
        <ul class="kt-menu__nav ">
            <li class="kt-menu__section ">
                <h4 class="kt-menu__section-text">Contact Management</h4>
                <i class="kt-menu__section-icon flaticon-more-v2"></i>
            </li>
            <li class="kt-menu__item  kt-menu__item--submenu" aria-haspopup="true" data-ktmenu-submenu-toggle="hover">
                <a href="{% url "contacts:list" %}" class="kt-menu__link kt-menu__toggle">
                    <i class="kt-menu__link-icon flaticon-users"></i>
                    <span class="kt-menu__link-text">Contact</span>
                    <i class="kt-menu__ver-arrow la la-angle-right"></i>
                </a>
                
            </li>
            
        </ul>
    </div>
</div>

risocrm/templates/partials/menus/setting_menu.html
{% load webpush_notifications %}

<div id="kt_quick_panel" class="kt-quick-panel">
        <a href="#" class="kt-quick-panel__close" id="kt_quick_panel_close_btn"><i class="flaticon2-delete"></i></a>
        <div class="kt-quick-panel__nav">
            <ul class="nav nav-tabs nav-tabs-line nav-tabs-bold nav-tabs-line-3x nav-tabs-line-brand  kt-notification-item-padding-x" role="tablist">
                <li class="nav-item active">
                    <a class="nav-link active" data-toggle="tab" href="#kt_quick_panel_tab_notifications" role="tab">Settings</a>
                </li>
            </ul>
        </div>
        <div class="kt-quick-panel__content">
            <div class="tab-content">
                <div class="tab-pane fade show kt-scroll active" id="kt_quick_panel_tab_notifications" role="tabpanel">
                    <div class="kt-notification">
                        {% webpush_button %}
                        {% if request.user.is_superuser %}
                        <a href="{% url 'users:list' %}" class="kt-notification__item">
                            <div class="kt-notification__item-icon">
                                <i class="flaticon-network kt-font-success"></i>
                            </div>
                            <div class="kt-notification__item-details">
                                <div class="kt-notification__item-title">
                                    Staff Management
                                </div>
                                <div class="kt-notification__item-time">
                                    Manage staff
                                </div>
                            </div>
                        </a>
                        {% endif %}
                        <a href="{% url 'choices:list' %}" class="kt-notification__item">
                            <div class="kt-notification__item-icon">
                                <i class="flaticon-map kt-font-danger"></i>
                            </div>
                            <div class="kt-notification__item-details">
                                <div class="kt-notification__item-title">
                                    Choice List
                                </div>
                                <div class="kt-notification__item-time">
                                    List choice collection for another Model
                                </div>
                            </div>
                        </a>
                        <a href="{% url 'app_mgmt:index' %}" class="kt-notification__item">
                            <div class="kt-notification__item-icon">
                                <i class="flaticon-interface-1 kt-font-success"></i>
                            </div>
                            <div class="kt-notification__item-details">
                                <div class="kt-notification__item-title">
                                    App Management
                                </div>
                                <div class="kt-notification__item-time">
                                    List App and field
                                </div>
                            </div>
                        </a>


                        <a href="{% url 'filters:list' %}" class="kt-notification__item">
                            <div class="kt-notification__item-icon">
                                <i class="flaticon2-sort-alphabetically kt-font-brand"></i>
                            </div>
                            <div class="kt-notification__item-details">
                                <div class="kt-notification__item-title">
                                    Filter Management
                                </div>
                                <div class="kt-notification__item-time">
                                    Advanced filter for each module
                                </div>
                            </div>
                        </a>


                        {% comment %} {% if request.user.is_superuser %}
                        <a href="{% url 'menus:list' %}" class="kt-notification__item">
                            <div class="kt-notification__item-icon">
                                <i class="flaticon2-menu kt-font-danger"></i>
                            </div>
                            <div class="kt-notification__item-details">
                                <div class="kt-notification__item-title">
                                    Menu Management
                                </div>
                                <div class="kt-notification__item-time">
                                    Enable/ Disable sorting Left menu
                                </div>
                            </div>
                        </a>
                        {% endif %} {% endcomment %}

                        
                        <a href="{% url 'dashboard:list' %}" class="kt-notification__item">
                            <div class="kt-notification__item-icon">
                                <i class="flaticon2-pie-chart kt-font-warning"></i>
                            </div>
                            <div class="kt-notification__item-details">
                                <div class="kt-notification__item-title">
                                    Dashboard Management
                                </div>
                                <div class="kt-notification__item-time">
                                    Manage report in dashboard
                                </div>
                            </div>
                        </a>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>